### ISSUE TITLE
【Bug】PPPoE Relay功能好像不可用

### ISSUE THREAD

**Issue by dingdang66686** [tsl0922/padavan#13]
使用hiboy的padavan可以正常relay，本固件开启PPPoE Relay功能后内网主机无法正常拨号，提示连接超时。

**Comment by tsl0922** [comment]
我这里测试可以。

4.4 内核版本 padavan 不支持内核级别的 pppoe-relay, 我只是把旧版本 padavan 的软件 relay 移植了过来，效果不太好，速度不是很快。

**Comment by dingdang66686** [comment]
好的，多谢。我现在改成switch直接配vlan了😂。
还有一个问题，为什么wan口会向192.168.1.10发arp报文？
