### ISSUE TITLE
能否集成tailscale

### ISSUE THREAD

**Issue by chenxudong2020** [tsl0922/padavan#15]
https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8279487&highlight=padavan%2Btailscale

自己装的话 闪存不够 希望集成进rom 
机型K2P

**Comment by tsl0922** [comment]
如果只是想把文件打包进固件，可以用：https://github.com/rampageX/firmware-mod-kit

go 的程序都很大，想把这个放进去就肯定要删其它的腾出空间。
