### ISSUE TITLE
可以考虑增加 禁用ipv6 nat 功能

### ISSUE THREAD

**Issue by blueststars** [tsl0922/padavan#9]
可以解决开启内网ipv6后有些网站卡的问题，MeIsReallyBa已经更新了使用良好。

**Comment by tsl0922** [comment]
你搞错了吧，人家是添加了 ipv6 nat  功能，默认禁用（和不支持一样）。

**Comment by blueststars** [comment]
> 你搞错了吧，人家是添加了 ipv6 nat 功能，默认禁用（和不支持一样）。

开启禁用ipv6 nat后就打开了内网IPV6,局域网下设备获取到公网ipv6地址，长期用下来正常。常规padavan固件直接开内网ipv6貌似有通病，访问一些网站图片不能正常显示、加载慢等，改dns也不能很好解决。
